"use client";
import {useMemo,useState} from "react";
import * as Dialog from "@radix-ui/react-dialog";
import * as Tooltip from "@radix-ui/react-tooltip";
import {AnimatePresence,motion} from "motion/react";
import {Activity,CalendarDays,Check,ChevronLeft,ChevronRight,Clock3,GraduationCap,HeartHandshake,Info,MapPin,Menu,Plus,Shirt,Sun,Users,X} from "lucide-react";

type Cat="giras"|"cursos"|"apometria"|"social";
type Item={id:number;day:number;title:string;time:string;cat:Cat;open:boolean;description:string};
const cats={
 giras:{label:"Giras e atividades espirituais",short:"Giras",color:"amber",Icon:Sun},
 cursos:{label:"Cursos e palestras",short:"Cursos",color:"orange",Icon:GraduationCap},
 apometria:{label:"Grupo de Apometria",short:"Apometria",color:"blue",Icon:Activity},
 social:{label:"Projetos sociais e Hospital Terapêutico",short:"Projetos sociais",color:"purple",Icon:HeartHandshake},
} satisfies Record<Cat,{label:string;short:string;color:string;Icon:typeof Sun}>;
const event=(id:number,day:number,title:string,time:string,cat:Cat,open=true,description="Atividade de acolhimento e cuidado promovida pela Casa Sol do Oriente."):Item=>({id,day,title,time,cat,open,description});
const events=[event(1,2,"Cirurgia Espiritual","19:30","giras"),event(2,4,"Desenvolvimento Mediúnico","19:00","cursos",false),event(3,5,"Gira de Caboclos","20:00","giras"),event(4,7,"Grupo de Apometria","14:00","apometria",false),event(5,8,"Hospital Terapêutico","09:00","social",true,"Terapias complementares e integrativas oferecidas por profissionais voluntários."),event(6,9,"Cirurgia Espiritual","19:30","giras"),event(7,11,"Espiritualidade no cotidiano","19:30","cursos"),event(8,12,"Gira de Pretos-Velhos","20:00","giras"),event(9,15,"A vida continua","15:00","social",true,"Roda de acolhimento para pessoas que atravessam processos de luto e transformação."),event(10,16,"Cirurgia Espiritual","19:30","giras"),event(11,18,"Orixás e suas forças","19:00","cursos",false),event(12,19,"Gira de Baianos","20:00","giras"),event(13,21,"Grupo de Apometria","14:00","apometria",false),event(14,22,"Firmando os trabalhos","10:00","social"),event(15,23,"Cirurgia Espiritual","19:30","giras"),event(16,25,"Roda de conversa: Caridade","19:30","cursos"),event(17,26,"Gira de Exus e Pombagiras","20:00","giras"),event(18,29,"Pão Solidário da Vó Margarida","08:30","social",false),event(19,30,"Cirurgia Espiritual","19:30","giras")];
const days=[...Array.from({length:6},(_,i)=>({n:26+i,out:true})),...Array.from({length:31},(_,i)=>({n:i+1,out:false})),...Array.from({length:3},(_,i)=>({n:i+1,out:true}))];
const weekday=(d:number)=>[2,9,16,23,30].includes(d)?"SEG":[4,11,18,25].includes(d)?"QUA":[5,12,19,26].includes(d)?"QUI":[7,21].includes(d)?"SÁB":[8,15,22,29].includes(d)?"DOM":"TER";
const google=(e:Item)=>{const d=String(e.day).padStart(2,"0"),s=e.time.replace(":","")+"00",end=String(+e.time.slice(0,2)+1).padStart(2,"0")+e.time.slice(3)+"00";return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(e.title)}&dates=202609${d}T${s}/202609${d}T${end}&details=${encodeURIComponent(e.description)}&location=${encodeURIComponent("Rua Francisco Nunes, 437 - Curitiba")}`};

export default function Home(){
 const [active,setActive]=useState(new Set<Cat>(["giras","cursos","apometria","social"]));
 const [selected,setSelected]=useState<Item|null>(null);const [menu,setMenu]=useState(false);
 const visible=useMemo(()=>events.filter(e=>active.has(e.cat)),[active]);
 const toggle=(c:Cat)=>setActive(old=>{const next=new Set(old);next.has(c)?next.delete(c):next.add(c);return next});
 return <Tooltip.Provider delayDuration={250}><div className="page">
  <header><div className="brand-icon"><Sun/></div><div className="brand"><strong>Casa Sol do Oriente</strong><span>Casa Universalista</span></div><nav><a>Início</a><a className="active">Calendário</a><a href="#orientacoes">Orientações</a><a href="#contato">Contato</a></nav><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Abrir menu">{menu?<X/>:<Menu/>}</button>{menu&&<motion.div className="mobile-nav" initial={{opacity:0,y:-6}} animate={{opacity:1,y:0}}><a>Início</a><a>Calendário</a><a href="#orientacoes">Orientações</a><a href="#contato">Contato</a></motion.div>}</header>
  <main><section className="hero"><motion.div initial={{opacity:0,y:16}} animate={{opacity:1,y:0}}><p className="eyebrow"><CalendarDays/> Agenda da Casa</p><h1>Calendário de<br/><em>Setembro</em></h1><p className="intro">Acompanhe nossas giras, cursos, palestras e projetos sociais. Encontre o seu momento de conexão, cuidado e partilha.</p></motion.div><motion.div className="sun-art" initial={{opacity:0,scale:.8,rotate:-15}} animate={{opacity:1,scale:1,rotate:0}}><i/><b/><Sun/></motion.div></section>
  <section className="calendar-section"><div className="toolbar"><div className="month"><Tip text="Mês anterior"><button aria-label="Mês anterior"><ChevronLeft/></button></Tip><div><span>Setembro</span><strong>2026</strong></div><Tip text="Próximo mês"><button aria-label="Próximo mês"><ChevronRight/></button></Tip><button className="today">Hoje</button></div><p><b>{visible.length}</b> atividades encontradas</p></div>
  <div className="filters"><span>Filtrar:</span>{(Object.keys(cats) as Cat[]).map(c=>{const x=cats[c],Icon=x.Icon,on=active.has(c);return <button key={c} className={`filter ${x.color} ${on?"":"off"}`} onClick={()=>toggle(c)} aria-pressed={on}><Icon/>{x.short}{on&&<Check/>}</button>})}<button className="clear" onClick={()=>setActive(new Set())}>Limpar filtros</button></div>
  <div className="calendar"><div className="week">{["DOM","SEG","TER","QUA","QUI","SEX","SÁB"].map(d=><div key={d}>{d}</div>)}</div><div className="grid">{days.map((d,i)=>{const list=d.out?[]:visible.filter(e=>e.day===d.n);return <div className={`cell ${d.out?"outside":""}`} key={i}><span className={d.n===8&&!d.out?"current":""}>{d.n}</span><div>{list.map(e=><EventCard key={e.id} item={e} onClick={()=>setSelected(e)}/>)}</div></div>})}</div></div>
  <div className="mobile-agenda">{Array.from({length:31},(_,i)=>i+1).map(day=>{const list=visible.filter(e=>e.day===day);return list.length?<div className="mobile-day" key={day}><div className="date"><strong>{String(day).padStart(2,"0")}</strong><span>{weekday(day)}</span></div><div>{list.map(e=><EventCard mobile key={e.id} item={e} onClick={()=>setSelected(e)}/>)}</div></div>:null})}</div></section>
  <section id="orientacoes" className="notice"><div><Info/><span><strong>Antes de vir à Casa</strong>Consulte as orientações de cada atividade e programe sua chegada com tranquilidade.</span></div><a href="https://www.casasoldooriente.com.br/gira.html" target="_blank" rel="noreferrer">Ver orientações gerais →</a></section></main>
  <footer id="contato"><div><Sun/><span><strong>Casa Sol do Oriente</strong><small>Amor, caridade e transformação.</small></span></div><p>Rua Francisco Nunes, 437 · Rebouças · Curitiba / PR</p><small>© 2026 Casa Universalista Sol do Oriente</small></footer>
  <Dialog.Root open={!!selected} onOpenChange={open=>!open&&setSelected(null)}><AnimatePresence>{selected&&<Dialog.Portal forceMount><Dialog.Overlay asChild><motion.div className="overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/></Dialog.Overlay><Dialog.Content asChild aria-describedby="description"><motion.div className="dialog" initial={{opacity:0,y:24,scale:.97}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:12,scale:.98}}><i className={`accent ${cats[selected.cat].color}`}/><Dialog.Close className="close" aria-label="Fechar"><X/></Dialog.Close><div className="dialog-title"><span className={`icon ${cats[selected.cat].color}`}>{(()=>{const Icon=cats[selected.cat].Icon;return <Icon/>})()}</span><div><small>{cats[selected.cat].label}</small><Dialog.Title>{selected.title}</Dialog.Title></div></div><div className="meta"><span><CalendarDays/> {selected.day} de setembro de 2026</span><span><Clock3/> {selected.time}</span><span><MapPin/> Casa Sol do Oriente</span></div><b className={`badge ${selected.open?"public":"closed"}`}><Users/>{selected.open?"Aberto ao público":"Fechado / com inscrição"}</b><Dialog.Description id="description">{selected.description}</Dialog.Description><div className="guidance"><h3><Shirt/> Orientações gerais</h3><p><Check/>Chegue com antecedência para o acolhimento</p><p><Check/>Use roupas confortáveis e discretas</p></div><a className="google" href={google(selected)} target="_blank" rel="noreferrer"><Plus/>Adicionar ao Google Agenda</a></motion.div></Dialog.Content></Dialog.Portal>}</AnimatePresence></Dialog.Root>
 </div></Tooltip.Provider>
}
function Tip({text,children}:{text:string;children:React.ReactNode}){return <Tooltip.Root><Tooltip.Trigger asChild>{children}</Tooltip.Trigger><Tooltip.Portal><Tooltip.Content className="tooltip" sideOffset={6}>{text}</Tooltip.Content></Tooltip.Portal></Tooltip.Root>}
function EventCard({item,onClick,mobile=false}:{item:Item;onClick:()=>void;mobile?:boolean}){const cat=cats[item.cat],Icon=cat.Icon;return <motion.button layout initial={{opacity:0,y:5}} animate={{opacity:1,y:0}} exit={{opacity:0,scale:.96}} whileHover={{y:-1}} className={`${mobile?"mobile-event":"event"} ${cat.color}`} onClick={onClick}><span><Icon/><b>{item.title}</b></span><small><Clock3/>{item.time}</small></motion.button>}
